-- Exemplo de inserção de categorias na tabela tb_categoria com IDs automáticos

INSERT INTO tb_categoria (nm_categoria) VALUES
('Romance'),
('Mistério'),
('Ficção Científica'),
('Fantasia'),
('Suspense'),
('Não Ficção'),
('Biografia'),
('História'),
('Autoajuda'),
('Poesia'),
('Livros Infantis'),
('Livros para Adolescentes'),
('Religião e Espiritualidade'),
('Ficção Histórica'),
('Ficção Contemporânea'),
('Política'),
('Filosofia'),
('Drama'),
('Horror'),
('Humor'),
('Graphic Novels'),
('Livros Didáticos'),
('Culinária e Gastronomia'),
('Arte e Fotografia'),
('Ciência'),
('Economia'),
('Psicologia'),
('Educação'),
('Teatro'),
('Música'),
('Esportes'),
('Saúde e Bem-Estar'),
('Meio Ambiente e Sustentabilidade'),
('Viagem'),
('Direito'),
('Arquitetura'),
('Tecnologia'),
('Computação e Programação'),
('Jornalismo'),
('Marketing'),
('Relações Internacionais'),
('Arqueologia'),
('Astrologia'),
('Mitologia'),
('Matemática'),
('Física'),
('Química'),
('Biologia'),
('Medicina'),
('Enfermagem');
